export interface IEditCalendar {
    LogID: string,
    LichID: string,
    ThoiGian: string,
    GhiChu: string,
    NguoiTao: string,
    NgayTao: string,
    DeviceID: string,
    NgaySuKien: string,
    IsReport: boolean,
    FileTep: string,
    DanhMucNhiemVuID: string,
    FileName: string,
    StatusID: string,
    NguyenNhan: string,
    NguoiTruc: string,
    FullName: string,
    DepartmentID: string,
    DepartmentName: string,
}