export interface IEditCalendar {
    LogID: TimeRanges,
    LichID: TimeRanges,
    ThoiGian: TimeRanges,
    GhiChu: TimeRanges,
    NguoiTao: TimeRanges,
    NgayTao: TimeRanges,
    DeviceID: TimeRanges,
    NgaySuKien: TimeRanges,
    IsReport: boolean,
    FileTep: TimeRanges,
    DanhMucNhiemVuID: TimeRanges,
    FileName: TimeRanges,
    StatusID: TimeRanges,
    NguyenNhan: TimeRanges,
    NguoiTruc: TimeRanges,
    FullName: TimeRanges,
    DepartmentID: TimeRanges,
    DepartmentName: TimeRanges,
}